version: '3'
services:
  shareplayer:
    #build: .
    image: bannsec/shareplayer:rewrite_gui
    ports:
        - "12345:12345"
    depends_on:
        - redis
    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"
    expose:
        - "6379"
